Branch person event manager
AY2425S1-CS2103T-T12-1/tp pull request #86
Opened 2024-10-21 14:20 UTC by antgyf

Proposing some preliminary changes to facilitate the association between people and events.

The proposed changes are laying the groundwork, more updates to the Commands will be added separately.

2024-10-21 14:25 UTC, FriedCabbageSalad requested changes
Some checkstyle errors

2024-10-21 14:25 UTC, FriedCabbageSalad commented on src/main/java/seedu/address/logic/commands/personcommands/EditPersonCommand.java
> +import static seedu.address.logic.parser.CliSyntax.*;
Avoid star imports

2024-10-21 14:25 UTC, FriedCabbageSalad commented on src/main/java/seedu/address/logic/parser/EditCommandParser.java
> +import static seedu.address.logic.parser.CliSyntax.*;
Star import here too

2024-10-21 14:25 UTC, FriedCabbageSalad commented on src/main/java/seedu/address/model/types/person/Person.java
> +    public Person(Name name, Phone phone, Email email, Address address, Set<Tag> tags, Event event) {
Missing java doc comment here

2024-10-21 14:25 UTC, FriedCabbageSalad commented on src/main/java/seedu/address/model/types/common/PersonEventManager.java
> +import java.util.HashMap;
Is this the correct import order?

2024-10-21 15:11 UTC, Jayden-Kim-NUS commented on src/main/java/seedu/address/logic/parser/CliSyntax.java
> +    public static final Prefix PREFIX_EVENT = new Prefix("ev/");
Should we consider make link to event a separate command instead of adding more prefixes?

2024-10-24 04:48 UTC, Jayden-Kim-NUS commented
LGTM

2024-10-24 04:49 UTC, merged